# Generated by Django 4.2.5 on 2023-09-14 16:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<div><p></p></div>', null=True),
        ),
    ]
