# Generated by Django 4.2.5 on 2023-09-12 10:16

import base.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=base.utils.rename_uploaded_file)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=base.utils.rename_uploaded_file)),
                ('nights', models.PositiveIntegerField()),
                ('number_of_hotels', models.PositiveIntegerField()),
                ('stay_mode', models.CharField(max_length=50)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations_theme', to='trips.packagetheme')),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations_type', to='trips.packagetype')),
            ],
        ),
    ]
