# Generated by Django 4.2.5 on 2023-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_packagetheme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetheme',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
